"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_routes_1 = __importDefault(require("./auth.routes"));
const user_routes_1 = __importDefault(require("./user.routes"));
const project_routes_1 = __importDefault(require("./project.routes"));
const categories_1 = __importDefault(require("./categories"));
const roles_routes_1 = __importDefault(require("./roles.routes"));
const teams_routes_1 = __importDefault(require("./teams.routes"));
const team_types_routes_1 = __importDefault(require("./team-types.routes"));
const partner_routes_1 = __importDefault(require("./partner.routes"));
const testimonial_routes_1 = __importDefault(require("./testimonial.routes"));
const faqs_1 = __importDefault(require("./faqs"));
const news_routes_1 = __importDefault(require("./news.routes"));
const opportunity_1 = __importDefault(require("./opportunity"));
const application_1 = __importDefault(require("./application"));
const contact_1 = __importDefault(require("./contact"));
const newsletter_1 = __importDefault(require("./newsletter"));
const upload_1 = __importDefault(require("./upload"));
const router = (0, express_1.Router)();
router.use("/auth", auth_routes_1.default);
router.use("/users", user_routes_1.default);
router.use("/projects", project_routes_1.default);
router.use("/categories", categories_1.default);
router.use("/roles", roles_routes_1.default);
router.use("/teams", teams_routes_1.default);
router.use("/team-types", team_types_routes_1.default);
router.use("/partners", partner_routes_1.default);
router.use("/testimonials", testimonial_routes_1.default);
router.use("/faqs", faqs_1.default);
router.use("/news", news_routes_1.default);
router.use("/opportunities", opportunity_1.default);
router.use("/applications", application_1.default);
router.use("/applications", opportunity_1.default);
router.use("/contacts", contact_1.default);
router.use("/newsletter", newsletter_1.default);
router.use("/uploads", upload_1.default);
exports.default = router;
