import { Task, TeamMember } from "./types";

export const initialMembers: TeamMember[] = [
  { id: "me", name: "Me", email: "me@example.com", color: "#8b5cf6", initials: "ME" },
  { id: "am", name: "Aimee Marie Ishimwe", email: "aimee@example.com", color: "#f59e0b", initials: "AM" },
  { id: "bk", name: "Baho Kemana Joselyto Charite", email: "baho@example.com", color: "#3b82f6", initials: "BK" },
  { id: "cm", name: "Comfort Mare", email: "comfort@example.com", color: "#10b981", initials: "CM" },
  { id: "sb", name: "Sarah Bamber", email: "sarah@example.com", color: "#ec4899", initials: "SB" },
  { id: "th", name: "Thierry", email: "thierry@example.com", color: "#f97316", initials: "TH" },
  { id: "jeannine", name: "Jeannine Uwase", email: "jeannine.uwase@gmail.com", color: "#2F88E1", initials: "JU" },
  { id: "hermione", name: "Hermione Merci", email: "murenzicharles24@gmail.com", color: "#8B5CF6", initials: "HM" },
  { id: "gentille", name: "Gentille Uwamahoro", email: "gentilleuwamahoro28@gmail.com", color: "#10B981", initials: "GU" },
];

const label = (name: string, color: string) => ({ id: `${name}-${color}`, name, color });

export const initialTasks: Task[] = [
  {
    id: "t1",
    title: "Design landing hero",
    description: "1. Research competitor hero sections\n2. Create mood board\n3. Sketch wireframes\n4. Design high-fidelity mockups\n5. Get stakeholder approval",
    deliverables: "- Final hero section design in Figma\n- Mobile and desktop variants\n- Assets exported for development\n- Design documentation",
    status: "overdue",
    priority: "high",
    dueDate: new Date(Date.now() + 86400000 * 3).toISOString(),
    labels: [label("design", "bg-fuchsia-200 text-fuchsia-800"), label("ui", "bg-blue-200 text-blue-800")],
    assignees: ["me", "am"],
    comments: [
      { id: "c1", userId: "am", message: "Draft ready", createdAt: new Date().toISOString() },
    ],
    attachments: [
      { id: "a1", filename: "hero.png", sizeKB: 512, uploadedAt: new Date().toISOString() },
    ],
  },
  {
    id: "t2",
    title: "API contract for tasks",
    description: "1. Define endpoint specifications\n2. Document request/response schemas\n3. Create OpenAPI documentation\n4. Review with team",
    deliverables: "- Complete API contract document\n- OpenAPI/Swagger spec file\n- Example requests and responses\n- Updated API documentation",
    status: "todo",
    priority: "medium",
    dueDate: new Date(Date.now() + 86400000 * 5).toISOString(),
    labels: [label("backend", "bg-emerald-200 text-emerald-800")],
    assignees: ["bk"],
    comments: [],
    attachments: [],
  },
  {
    id: "t3",
    title: "Setup CI",
    status: "todo",
    priority: "low",
    dueDate: new Date(Date.now() + 86400000 * 8).toISOString(),
    labels: [label("devops", "bg-slate-200 text-slate-800")],
    assignees: ["th"],
    comments: [],
    attachments: [],
  },
  {
    id: "t4",
    title: "Build Kanban board",
    description: "1. Implement drag-and-drop functionality\n2. Add column management\n3. Create task cards\n4. Add filters and search\n5. Test on different browsers",
    deliverables: "- Fully functional Kanban board\n- Smooth drag-and-drop experience\n- Responsive design\n- Unit and integration tests",
    status: "inprogress",
    priority: "high",
    dueDate: new Date(Date.now() + 86400000 * 2).toISOString(),
    labels: [label("feature", "bg-indigo-200 text-indigo-800")],
    assignees: ["me", "cm"],
    comments: [{ id: "c2", userId: "me", message: "Drag works", createdAt: new Date().toISOString() }],
    attachments: [],
  },
  {
    id: "t5",
    title: "Task modal interactions",
    status: "inprogress",
    priority: "medium",
    dueDate: new Date(Date.now() + 86400000 * 4).toISOString(),
    labels: [label("ui", "bg-blue-200 text-blue-800"), label("ux", "bg-rose-200 text-rose-800")],
    assignees: ["sb"],
    comments: [],
    attachments: [{ id: "a2", filename: "wireframe.pdf", sizeKB: 220, uploadedAt: new Date().toISOString() }],
  },
  {
    id: "t6",
    title: "Review accessibility",
    status: "review",
    priority: "low",
    dueDate: new Date(Date.now() + 86400000 * 6).toISOString(),
    labels: [label("a11y", "bg-amber-200 text-amber-900")],
    assignees: ["cm"],
    comments: [{ id: "c3", userId: "cm", message: "Contrast ok", createdAt: new Date().toISOString() }],
    attachments: [],
  },
  {
    id: "t7",
    title: "Team view metrics",
    status: "review",
    priority: "medium",
    dueDate: new Date(Date.now() + 86400000 * 7).toISOString(),
    labels: [label("analytics", "bg-cyan-200 text-cyan-900")],
    assignees: ["bk", "sb"],
    comments: [],
    attachments: [],
  },
  {
    id: "t8",
    title: "Deploy preview",
    status: "done",
    priority: "low",
    dueDate: new Date(Date.now() - 86400000 * 1).toISOString(),
    labels: [label("infra", "bg-zinc-200 text-zinc-800")],
    assignees: ["th"],
    comments: [{ id: "c4", userId: "th", message: "Shipped", createdAt: new Date().toISOString() }],
    attachments: [],
  },
  {
    id: "t9",
    title: "Write docs",
    status: "overdue",
    priority: "medium",
    dueDate: undefined,
    labels: [label("docs", "bg-violet-200 text-violet-900")],
    assignees: ["me"],
    comments: [],
    attachments: [],
  },
  {
    id: "t10",
    title: "Database optimization",
    status: "todo",
    priority: "high",
    dueDate: new Date(Date.now() + 86400000 * 15).toISOString(),
    labels: [label("database", "bg-red-200 text-red-800")],
    assignees: ["bk", "th"],
    comments: [],
    attachments: [],
  },
  {
    id: "t11",
    title: "Security audit",
    status: "overdue",
    priority: "medium",
    dueDate: new Date(Date.now() + 86400000 * 20).toISOString(),
    labels: [label("security", "bg-orange-200 text-orange-800")],
    assignees: ["cm"],
    comments: [],
    attachments: [],
  },
  {
    id: "t12",
    title: "Performance testing",
    status: "todo",
    priority: "low",
    dueDate: new Date(Date.now() + 86400000 * 12).toISOString(),
    labels: [label("testing", "bg-green-200 text-green-800")],
    assignees: ["am", "sb"],
    comments: [],
    attachments: [],
  },
  {
    id: "t13",
    title: "Code review process",
    status: "inprogress",
    priority: "medium",
    dueDate: new Date(Date.now() + 86400000 * 7).toISOString(),
    labels: [label("process", "bg-blue-200 text-blue-800")],
    assignees: ["me", "bk"],
    comments: [],
    attachments: [],
  },
  {
    id: "t14",
    title: "Deployment pipeline",
    status: "review",
    priority: "high",
    dueDate: new Date(Date.now() + 86400000 * 10).toISOString(),
    labels: [label("deployment", "bg-purple-200 text-purple-800")],
    assignees: ["th"],
    comments: [],
    attachments: [],
  },
  {
    id: "t15",
    title: "User feedback collection",
    status: "done",
    priority: "low",
    dueDate: new Date(Date.now() + 86400000 * 5).toISOString(),
    labels: [label("feedback", "bg-yellow-200 text-yellow-800")],
    assignees: ["sb", "cm"],
    comments: [],
    attachments: [],
  },
];


